"""Small surface-input extension of this project's installed URP Lit shader.

The lighting, shadow, depth and GBuffer implementations remain URP's PBR.
Only texture frequency, restrained albedo treatment and roughness are adjusted.
No toon bands, outlines, fake rim lights or baked lighting are introduced.
"""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[3]
PACKAGE=ROOT/'Library/PackageCache/com.unity.render-pipelines.universal@d7774c218bdf'
OUT=ROOT/'Assets/SilverScreen/Art/Characters/Canonical/Shaders'
OUT.mkdir(parents=True,exist_ok=True)
shader=(PACKAGE/'Shaders/Lit.shader').read_text()
inputs=(PACKAGE/'Shaders/LitInput.hlsl').read_text()
shader=shader.replace('Shader "Universal Render Pipeline/Lit"','Shader "SilverScreen/Characters/Restrained Realism"',1)
properties='''
        _SSFilter("Photographic detail reduction", Range(0,1)) = 0
        _SSMip("Minimum surface detail mip", Range(0,6)) = 0
        _SSNormalMip("Normal detail mip", Range(0,6)) = 0
        _SSColorBalance("Linear colour balance", Vector) = (1,1,1,0)
        _SSValuePivot("Value pivot", Float) = .25
        _SSContrast("Texture value contrast", Range(.5,1.1)) = 1
        _SSFeatureL("Left eye/brow UV preserve", Vector) = (0,0,.001,.001)
        _SSFeatureR("Right eye/brow UV preserve", Vector) = (0,0,.001,.001)
        _SSFeatureMouth("Mouth UV preserve", Vector) = (0,0,.001,.001)
        _SSFeatureNose("Nose UV preserve", Vector) = (0,0,.001,.001)
'''
shader=shader.replace('        // Specular vs Metallic workflow',properties+'\n        // Specular vs Metallic workflow',1)
shader=shader.replace('#include "LitInput.hlsl"','#include "CanonicalLitInput.hlsl"')
shader=shader.replace('#include "Packages/com.unity.render-pipelines.universal/Shaders/LitInput.hlsl"','#include "CanonicalLitInput.hlsl"')
assert '#include "CanonicalLitInput.hlsl"' in shader
# Package files use relative includes; retain upstream implementations in place.
import re
shader=re.sub(r'#include "(?!Packages/|CanonicalLitInput)([^"/]+\.hlsl)"',r'#include "Packages/com.unity.render-pipelines.universal/Shaders/\1"',shader)
fields='''
float _SSFilter, _SSMip, _SSNormalMip, _SSValuePivot, _SSContrast;
float4 _SSColorBalance, _SSFeatureL, _SSFeatureR, _SSFeatureMouth, _SSFeatureNose;
'''
inputs=inputs.replace('CBUFFER_START(UnityPerMaterial)','CBUFFER_START(UnityPerMaterial)\n'+fields,1)
helpers='''
// Ellipses preserve authored brows, lids and lip/nostril boundaries while the
// broad skin surface loses photographic pores and individual stubble dots.
float SSPreserveFeature(float2 uv, float4 region)
{
    float2 p=(uv-region.xy)/max(region.zw,float2(.0001,.0001));
    return exp(-2.0*dot(p,p));
}
half3 SSArtDirectedAlbedo(float2 uv, half3 original)
{
    float preserve=max(max(SSPreserveFeature(uv,_SSFeatureL),SSPreserveFeature(uv,_SSFeatureR)),
                       max(SSPreserveFeature(uv,_SSFeatureMouth),SSPreserveFeature(uv,_SSFeatureNose)));
    float2 dx=ddx(uv*_BaseMap_TexelSize.zw),dy=ddy(uv*_BaseMap_TexelSize.zw);
    float pixelMip=.5*log2(max(max(dot(dx,dx),dot(dy,dy)),.0001));
    half3 broad=SAMPLE_TEXTURE2D_LOD(_BaseMap,sampler_BaseMap,uv,max(_SSMip,pixelMip)).rgb;
    half3 colour=lerp(original,broad,_SSFilter*(1-.88*preserve));
    // Compress albedo variation slightly without flattening the real lighting.
    colour=max(0,(colour-_SSValuePivot)*_SSContrast+_SSValuePivot);
    return colour*_SSColorBalance.rgb;
}
'''
inputs=inputs.replace('inline void InitializeStandardLitSurfaceData',helpers+'\ninline void InitializeStandardLitSurfaceData',1)
inputs=inputs.replace('outSurfaceData.albedo = albedoAlpha.rgb * _BaseColor.rgb;','outSurfaceData.albedo = SSArtDirectedAlbedo(uv,albedoAlpha.rgb) * _BaseColor.rgb;',1)
normal='''
#if defined(_NORMALMAP)
    if (_SSNormalMip > 0)
    {
        float2 dx=ddx(uv*_BaseMap_TexelSize.zw),dy=ddy(uv*_BaseMap_TexelSize.zw);
        float pixelMip=.5*log2(max(max(dot(dx,dx),dot(dy,dy)),.0001));
        half4 normalData=SAMPLE_TEXTURE2D_LOD(_BumpMap,sampler_BumpMap,uv,max(_SSNormalMip,pixelMip));
        half3 broadNormal=UnpackNormalScale(normalData,_BumpScale);
        outSurfaceData.normalTS=normalize(lerp(outSurfaceData.normalTS,broadNormal,_SSFilter));
    }
#endif
'''
needle='    outSurfaceData.occlusion = SampleOcclusion(uv);'
assert needle in inputs
inputs=inputs.replace(needle,normal+'\n'+needle,1)
header='// Derived from installed Unity URP Lit. Unity Technologies copyright; Unity Companion License.\n// Generated by ArtSource/Characters/Canonical/build_study_shader.py.\n'
(OUT/'CanonicalLit.shader').write_text(header+shader)
(OUT/'CanonicalLitInput.hlsl').write_text(header+inputs)
(OUT/'UnityCompanionLicense.txt').write_text((PACKAGE/'LICENSE.md').read_text(encoding='utf-8'),encoding='utf-8')
report={'package':str(PACKAGE.relative_to(ROOT)),'upstream_sha256':{name:hashlib.sha256((PACKAGE/'Shaders'/name).read_bytes()).hexdigest() for name in ('Lit.shader','LitInput.hlsl')},'lighting':'unchanged URP PBR; material input frequency treatment only'}
(ROOT/'ArtSource/Characters/Canonical/shader_provenance.json').write_text(json.dumps(report,indent=2))
