using System.Linq;
using SilverScreen.Domain;
using SilverScreen.Domain.Recruitment;
using SilverScreen.Presentation.Recruitment;
using SilverScreen.Presentation.Selection;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
namespace SilverScreen.Presentation.UI
{
 public sealed class RecruitmentPanelUI:MonoBehaviour
 {
  private RecruitmentDriver _driver;private StudioSelectionController _selection;private GameObject _root;private RectTransform _content;private TextMeshProUGUI _detail;
  public void Initialize(RecruitmentDriver driver){_driver=driver;_selection=FindAnyObjectByType<StudioSelectionController>();Build();Bind();Refresh();}
  private void OnDestroy(){if(_driver?.Coordinator!=null){_driver.Coordinator.OnCandidateAdded-=Changed;_driver.Coordinator.OnCandidateChanged-=Changed;_driver.Coordinator.OnCandidateRemoved-=Changed;}if(_selection!=null){_selection.OnCandidateSelectionChanged-=SelectedCandidate;_selection.OnStageSchoolSelectionChanged-=SelectedSchool;}}
  private void Build(){var canvas=FindAnyObjectByType<Canvas>();if(canvas==null)return;var rect=ManagementUIFactory.Rect("StageSchoolRecruitment",canvas.transform,new Vector2(.56f,.08f),new Vector2(.98f,.90f),Vector2.zero,Vector2.zero);_root=rect.gameObject;ManagementUIFactory.Background(rect,ManagementUIFactory.Panel);var titleRect=ManagementUIFactory.Rect("Title",rect,new Vector2(0,1),new Vector2(1,1),new Vector2(0,-32),new Vector2(-30,54));var title=ManagementUIFactory.Text("Text",titleRect,"STAGE SCHOOL — TALENT",24,TextAlignmentOptions.Center,ManagementUIFactory.Gold);title.fontStyle=FontStyles.Bold;var closeRect=ManagementUIFactory.Rect("Close",rect,new Vector2(1,1),new Vector2(1,1),new Vector2(-28,-24),new Vector2(42,38));var close=ManagementUIFactory.Button("Button",closeRect,"×",ManagementUIFactory.PanelRaised,Color.white);close.onClick.AddListener(()=>_root.SetActive(false));var listRect=ManagementUIFactory.Rect("List",rect,new Vector2(.03f,.34f),new Vector2(.97f,.88f),Vector2.zero,Vector2.zero);ManagementUIFactory.ScrollView("Scroll",listRect,out _content);var detailRect=ManagementUIFactory.Rect("Detail",rect,new Vector2(.04f,.05f),new Vector2(.96f,.31f),Vector2.zero,Vector2.zero);ManagementUIFactory.Background(detailRect,ManagementUIFactory.PanelRaised);_detail=ManagementUIFactory.Text("Text",detailRect,"Select a candidate",14,TextAlignmentOptions.MidlineLeft,Color.white);ManagementUIFactory.SetOffsets(_detail.rectTransform,16,12,16,12);_root.SetActive(false);}
  private void Bind(){if(_driver?.Coordinator!=null){_driver.Coordinator.OnCandidateAdded+=Changed;_driver.Coordinator.OnCandidateChanged+=Changed;_driver.Coordinator.OnCandidateRemoved+=Changed;}if(_selection!=null){_selection.OnCandidateSelectionChanged+=SelectedCandidate;_selection.OnStageSchoolSelectionChanged+=SelectedSchool;}}
  private void Changed(Candidate unused)=>Refresh();private void SelectedSchool(StageSchoolView school){if(school==null||school!=_driver.StageSchool)return;_root.SetActive(true);Refresh();}private void SelectedCandidate(CandidateAgent agent){if(agent?.Candidate==null)return;_root.SetActive(true);Show(agent.Candidate);Refresh();}
  private void Refresh(){if(_content==null||_driver?.Coordinator==null)return;foreach(Transform child in _content)Destroy(child.gameObject);foreach(var candidate in _driver.Coordinator.Candidates)CreateRow(candidate);if(_driver.Coordinator.Candidates.Count==0){var empty=ManagementUIFactory.Rect("Empty",_content,Vector2.zero,Vector2.one,Vector2.zero,new Vector2(0,48));empty.gameObject.AddComponent<LayoutElement>().preferredHeight=48;ManagementUIFactory.Text("Text",empty,"No candidates are currently waiting.",14,TextAlignmentOptions.Center,ManagementUIFactory.Muted);}}
  private void CreateRow(Candidate candidate){var row=ManagementUIFactory.Rect("Candidate_"+candidate.Person.Id,_content,Vector2.zero,Vector2.one,Vector2.zero,new Vector2(0,64));row.gameObject.AddComponent<LayoutElement>().preferredHeight=64;ManagementUIFactory.Background(row,ManagementUIFactory.PanelRaised);var info=ManagementUIFactory.Rect("Info",row,new Vector2(0,0),new Vector2(.55f,1),Vector2.zero,Vector2.zero);ManagementUIFactory.SetOffsets(info,12,4,4,4);ManagementUIFactory.Text("Text",info,$"<b>{candidate.Person.Name}</b>  •  {candidate.Person.ProfessionalRole}\n{candidate.Status}  •  ${candidate.SalaryExpectation:N0}/month",13,TextAlignmentOptions.MidlineLeft,Color.white);MakeButton(row,.56f,.70f,"VIEW",()=>{Show(candidate);var agent=_driver.WorldRouter.GetAgent(candidate);if(agent!=null)_selection.Select(agent);});MakeButton(row,.71f,.84f,"HIRE",()=>{_driver.Coordinator.Hire(candidate);Show(null);Refresh();});MakeButton(row,.85f,.98f,"REJECT",()=>{_driver.Coordinator.Reject(candidate);Show(null);Refresh();});}
  private static void MakeButton(Transform row,float min,float max,string label,UnityEngine.Events.UnityAction action){var rect=ManagementUIFactory.Rect(label,row,new Vector2(min,.18f),new Vector2(max,.82f),Vector2.zero,Vector2.zero);var button=ManagementUIFactory.Button("Button",rect,label,label=="HIRE"?ManagementUIFactory.Gold:ManagementUIFactory.Panel,Color.white);button.onClick.AddListener(action);}
  private void Show(Candidate candidate){if(_detail==null)return;if(candidate==null){_detail.text="Select a candidate";return;}var p=candidate.Person;int age=p.GetAge(_driver.CurrentTime);string genres=string.Join(", ",p.Talent.GenreExperience.OrderByDescending(x=>x.Experience).Take(3).Select(x=>$"{x.GenreId} {x.Experience}"));_detail.text=$"<b>{p.Name}</b> — Age {age} — {p.ProfessionalRole}\nSalary expectation: ${candidate.SalaryExpectation:N0}/month\nActing {p.Talent.ActingAbility}  |  Directing {p.Talent.DirectingAbility}\nExperience: {genres}\nTraits: {string.Join(", ",p.TraitIds)}\nStatus: {candidate.Status}";}
 }
}