using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using SilverScreen.Domain;
using SilverScreen.Domain.Finance;
using SilverScreen.Domain.Recruitment;
using SilverScreen.Domain.Time;
namespace SilverScreen.Tests
{
 public sealed class RecruitmentTests
 {
  private static SimulationDateTime Now=>new SimulationDateTime(1930,1,1,8,0);
  [Test] public void PersonAgeUsesSimulationDate(){var p=Person("p",ProfessionalRole.Actor);Assert.AreEqual(30,p.GetAge(Now));Assert.AreEqual(29,p.GetAge(new SimulationDateTime(1929,12,31,0,0)));}
  [Test] public void TalentStoresStableGenreExperienceAndTraits(){var p=Person("p",ProfessionalRole.Actor);Assert.AreEqual(42,p.Talent.GetGenreExperience("drama"));CollectionAssert.Contains(p.TraitIds,PersonTraitIds.Disciplined);}
  [Test] public void GeneratorIsDeterministicForKnownSeed(){var a=new CandidateGenerator(new SeededRandomSource(77)).Generate(Now);var b=new CandidateGenerator(new SeededRandomSource(77)).Generate(Now);Assert.AreEqual(a.Person.Id,b.Person.Id);Assert.AreEqual(a.Person.Name,b.Person.Name);Assert.AreEqual(a.Person.ProfessionalRole,b.Person.ProfessionalRole);Assert.AreEqual(a.SalaryExpectation,b.SalaryExpectation);}
  [Test] public void GeneratedCandidatesHaveValidRoleSalaryAndTraits(){var g=new CandidateGenerator(new SeededRandomSource(12));for(int i=0;i<30;i++){var c=g.Generate(Now);Assert.Contains(c.Person.ProfessionalRole,new[]{ProfessionalRole.Actor,ProfessionalRole.Director,ProfessionalRole.Extra,ProfessionalRole.Writer});Assert.Greater(c.SalaryExpectation,0);Assert.That(c.Person.TraitIds.Count,Is.InRange(1,3));}}
  [Test] public void GeneratorCanProduceVaryingExperience(){var g=new CandidateGenerator(new SeededRandomSource(99));var values=Enumerable.Range(0,40).Select(_=>g.Generate(Now).Person.Talent.GetGenreExperience("drama")).Distinct().Count();Assert.Greater(values,3);}
  [Test] public void CandidateLifecycleAcceptsOnlyValidTransitions(){var c=new Candidate(Person("p",ProfessionalRole.Actor),1000);Assert.IsFalse(c.MarkHired());Assert.IsTrue(c.MarkWaiting(0));Assert.IsFalse(c.MarkWaiting(1));Assert.IsTrue(c.BeginDeparture());Assert.IsFalse(c.MarkHired());Assert.IsTrue(c.MarkGone());}
  [Test] public void HirePreservesPersonIdentityAndCreatesEmployee(){var setup=Setup(ProfessionalRole.Actor);var id=setup.candidate.Person.Id;var employee=setup.coordinator.Hire(setup.candidate);Assert.AreEqual(CandidateStatus.Hired,setup.candidate.Status);Assert.AreSame(setup.candidate.Person,employee.Person);Assert.AreEqual(id,employee.Id);Assert.AreEqual(EmployeeRole.Actor,employee.Role);}
  [Test] public void DirectorAndExtraMapToCorrectEmployeeRoles(){var director=Setup(ProfessionalRole.Director);Assert.AreEqual(EmployeeRole.Director,director.coordinator.Hire(director.candidate).Role);var extra=Setup(ProfessionalRole.Extra);Assert.AreEqual(EmployeeRole.Extra,extra.coordinator.Hire(extra.candidate).Role);}
  [Test] public void CandidateIsNotPayrollUntilHiredAndSalaryProcessesOnce(){var setup=Setup(ProfessionalRole.Actor);var employees=new List<Employee>();var finances=new StudioFinances(Now,Money.FromDollars(10000));using var accounting=new StudioAccountingService(setup.clock,finances,()=>employees,()=>Array.Empty<BuildingUpkeepDefinition>());Assert.AreEqual(Money.Zero,accounting.EstimatedMonthlyPayroll);var employee=setup.coordinator.Hire(setup.candidate);employees.Add(employee);Assert.AreEqual(Money.FromDollars(employee.Salary),accounting.EstimatedMonthlyPayroll);var date=new SimulationDateTime(1930,2,1,0,0);Assert.IsTrue(accounting.ProcessMonthlyAccounting(date));Assert.IsFalse(accounting.ProcessMonthlyAccounting(date));Assert.AreEqual(1,finances.Transactions.Count(x=>x.Category==FinancialTransactionCategory.EmployeeSalary));}
  [Test] public void RejectionRoutesCandidateToGone(){var setup=Setup(ProfessionalRole.Actor);Assert.IsTrue(setup.coordinator.Reject(setup.candidate));Assert.AreEqual(CandidateStatus.Gone,setup.candidate.Status);Assert.IsEmpty(setup.coordinator.Candidates);}
  [Test] public void ArrivalRoutingFailureRemovesCandidateSafely(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{ArrivalResult=CandidateRouteResult.NavigationRejected};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(1)),router,new RecruitmentConfiguration());var c=coordinator.TryGenerateArrival();Assert.AreEqual(CandidateStatus.Gone,c.Status);CollectionAssert.DoesNotContain(coordinator.Candidates,c);Assert.AreEqual(1,router.Released);}
  [Test] public void DepartureRoutingFailureRemovesCandidateSafely(){var setup=Setup(ProfessionalRole.Actor);setup.router.DepartureResult=CandidateRouteResult.NavigationRejected;Assert.IsTrue(setup.coordinator.Reject(setup.candidate));Assert.AreEqual(CandidateStatus.Gone,setup.candidate.Status);Assert.IsEmpty(setup.coordinator.Candidates);}
  [Test] public void CapacityIsRespectedAndWaitingSlotsAreUnique(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(3)),router,new RecruitmentConfiguration(2,999,999));var a=coordinator.TryGenerateArrival();var b=coordinator.TryGenerateArrival();Assert.IsNull(coordinator.TryGenerateArrival());Assert.AreNotEqual(a.WaitingPositionIndex,b.WaitingPositionIndex);}
  [Test] public void StarterPoliciesUseTheApprovedCategoryCountsAndTiming(){var policies=RecruitmentCategoryConfiguration.CreateStarterIntakeDefaults().ToDictionary(x=>x.Category);Assert.AreEqual(6,policies[RecruitmentCategory.StudioServices].StarterApplicantCount);Assert.AreEqual(4,policies[RecruitmentCategory.Talent].StarterApplicantCount);Assert.AreEqual(4,policies[RecruitmentCategory.Crew].StarterApplicantCount);Assert.AreEqual(3,policies[RecruitmentCategory.Writing].StarterApplicantCount);foreach(var policy in policies.Values){Assert.AreEqual(1,policy.FirstStarterDelayMinutes);Assert.AreEqual(8,policy.StarterSpacingMinutes);Assert.AreEqual(30,policy.RetryDelayMinutes);}Assert.AreEqual(180,policies[RecruitmentCategory.Talent].ArrivalCadenceMinutes);}
  [Test] public void TalentStarterDispatchesAtOneNineSeventeenAndTwentyFiveMinutes(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,4,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(38)),router,config);var scheduled=new List<SimulationDateTime>();coordinator.OnCandidateAdded+=candidate=>scheduled.Add(clock.CurrentTime);AdvanceMinutes(clock,33);CollectionAssert.AreEqual(new[]{new SimulationDateTime(1930,1,1,8,1),new SimulationDateTime(1930,1,1,8,9),new SimulationDateTime(1930,1,1,8,17),new SimulationDateTime(1930,1,1,8,25)},scheduled);Assert.AreEqual(4,coordinator.Candidates.Select(x=>x.Person.Id).Distinct().Count());Assert.IsTrue(coordinator.Candidates.All(x=>x.Category==RecruitmentCategory.Talent&&x.Person.ProfessionalRole!=ProfessionalRole.Writer&&x.Person.ProfessionalRole!=ProfessionalRole.Crew));}
  [Test] public void ReplacingAndReenablingFacilityDoesNotRegrantTalentStarters(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{Capacity=2};var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,4,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(39)),router,config);var arrivals=new List<Candidate>();coordinator.OnCandidateAdded+=arrivals.Add;AdvanceMinutes(clock,17);Assert.AreEqual(2,coordinator.Candidates.Count);Assert.AreEqual(2,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);router.Operational=false;AdvanceMinutes(clock,10);router.Operational=true;Assert.AreEqual(2,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.NotNull(coordinator.Hire(coordinator.Candidates[0]));AdvanceMinutes(clock,1);Assert.AreEqual(3,arrivals.Count);Assert.AreEqual(1,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.NotNull(coordinator.Hire(coordinator.Candidates[0]));AdvanceMinutes(clock,8);Assert.AreEqual(4,arrivals.Count);Assert.AreEqual(0,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);router.Operational=false;router.Operational=true;AdvanceMinutes(clock,8);Assert.AreEqual(4,arrivals.Count);}
  [Test] public void StudioServicesReceivesOneSixApplicantIntakeBeforeNormalCadence(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.StudioServices,6,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(36)),router,config);AdvanceMinutes(clock,41);Assert.AreEqual(6,coordinator.Candidates.Count);Assert.AreEqual(6,coordinator.Candidates.Count(x=>x.IsStarterApplicant));Assert.AreEqual(0,coordinator.IntakeStates[RecruitmentCategory.StudioServices].StarterApplicantsRemaining);var hired=coordinator.Hire(coordinator.Candidates[0]);Assert.NotNull(hired);Assert.AreEqual(1,router.Released);Assert.AreEqual(5,coordinator.Candidates.Count);AdvanceMinutes(clock,179);Assert.AreEqual(5,coordinator.Candidates.Count);AdvanceMinutes(clock,1);Assert.AreEqual(6,coordinator.Candidates.Count);Assert.AreEqual(5,coordinator.Candidates.Count(x=>x.IsStarterApplicant));router.Operational=false;router.Operational=true;Assert.AreEqual(0,coordinator.IntakeStates[RecruitmentCategory.StudioServices].StarterApplicantsRemaining);}
  [Test] public void StarterIntakeWaitsForOperationalFacilityAndNormalCadenceFollowsCompletion(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{Operational=false};var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,4,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(31)),router,config);AdvanceMinutes(clock,1);Assert.IsFalse(coordinator.IntakeStates[RecruitmentCategory.Talent].StarterGrantTriggered);Assert.AreEqual(0,coordinator.Candidates.Count);router.Operational=true;Assert.IsTrue(coordinator.IntakeStates[RecruitmentCategory.Talent].StarterGrantTriggered);Assert.AreEqual(0,coordinator.Candidates.Count);AdvanceMinutes(clock,1);Assert.AreEqual(1,coordinator.Candidates.Count);for(int i=0;i<3;i++)AdvanceMinutes(clock,8);Assert.AreEqual(4,coordinator.Candidates.Count);Assert.AreEqual(0,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.AreEqual(4,coordinator.Candidates.Count(x=>x.IsStarterApplicant));var snapshot=coordinator.CaptureSnapshot();coordinator.Dispose();using var restored=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(32)),router,config,snapshot);AdvanceMinutes(clock,179);Assert.AreEqual(0,restored.Candidates.Count);AdvanceMinutes(clock,1);Assert.AreEqual(1,restored.Candidates.Count);Assert.IsFalse(restored.Candidates[0].IsStarterApplicant);}
  [Test] public void StarterIntakeKeepsUndeliveredApplicantsWhenCapacityIsFull(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{Capacity=0};var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,4,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(33)),router,config);AdvanceMinutes(clock,2);Assert.AreEqual(4,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.AreEqual(0,coordinator.Candidates.Count);router.Capacity=6;AdvanceMinutes(clock,1);Assert.AreEqual(1,coordinator.Candidates.Count);Assert.AreEqual(3,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);}
  [Test] public void PendingIntakeSurvivesSnapshotAndFacilityReplacement(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{Capacity=0};var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,4,1,8,180)};var original=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(40)),router,config);AdvanceMinutes(clock,1);var snapshot=original.CaptureSnapshot();original.Dispose();router.Operational=false;using var restored=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(41)),router,config,snapshot);AdvanceMinutes(clock,10);Assert.AreEqual(4,restored.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);router.Capacity=6;router.Operational=true;AdvanceMinutes(clock,1);Assert.AreEqual(3,restored.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.AreEqual(1,restored.Candidates.Count);}
  [Test] public void SlowPhysicalJourneysDoNotCreateExtraStarters(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{DeferArrival=true};var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,4,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(42)),router,config);AdvanceMinutes(clock,40);Assert.AreEqual(4,coordinator.Candidates.Count);Assert.AreEqual(4,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.AreEqual(4,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsInFlight);router.CompleteArrivals();Assert.AreEqual(0,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.IsTrue(coordinator.Candidates.All(x=>x.Status==CandidateStatus.WaitingForRecruitment));}
  [Test] public void FailedStarterJourneyRetriesAfterThirtySimulationMinutes(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{ArrivalResult=CandidateRouteResult.NavigationRejected};var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,4,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(34)),router,config);AdvanceMinutes(clock,1);Assert.AreEqual(4,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);Assert.AreEqual(30,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterRetryMinutes);router.ArrivalResult=CandidateRouteResult.Started;AdvanceMinutes(clock,29);Assert.AreEqual(0,coordinator.Candidates.Count);AdvanceMinutes(clock,1);Assert.AreEqual(1,coordinator.Candidates.Count);Assert.AreEqual(3,coordinator.IntakeStates[RecruitmentCategory.Talent].StarterApplicantsRemaining);}
  [Test] public void ThreeTimesSpeedUsesAuthoritativeSimulationMinuteBoundaries(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);clock.SetSpeed(SimulationSpeed.VeryFast);var router=new FakeRouter();var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,1,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(35)),router,config);int elapsedMinutes=0;clock.OnMinutePassed+=_=>elapsedMinutes++;clock.Advance(.01f);Assert.AreEqual(0,elapsedMinutes);Assert.IsEmpty(coordinator.Candidates);clock.Advance(.01f);Assert.AreEqual(1,elapsedMinutes);Assert.AreEqual(1,coordinator.Candidates.Count);Assert.IsTrue(coordinator.Candidates[0].IsStarterApplicant);}
  [Test] public void PauseStopsStarterClockAndDoubleSpeedAdvancesOneSimulationMinute(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);clock.SetSpeed(SimulationSpeed.Paused);var router=new FakeRouter();var config=new[]{new RecruitmentCategoryConfiguration(RecruitmentCategory.Talent,1,1,8,180)};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(37)),router,config);clock.Advance(2f);Assert.AreEqual(0,coordinator.Candidates.Count);clock.SetSpeed(SimulationSpeed.Fast);clock.Advance(clock.RealSecondsPerSimulatedMinute/2f);Assert.AreEqual(1,coordinator.Candidates.Count);}
  [Test] public void WaitingCandidateAutomaticallyExpires(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(4)),router,new RecruitmentConfiguration(5,999,60));var c=coordinator.TryGenerateArrival();for(int i=0;i<60;i++)clock.Advance(.05f);Assert.AreEqual(CandidateStatus.Gone,c.Status);CollectionAssert.DoesNotContain(coordinator.Candidates,c);}
  private static void AdvanceMinutes(SimulationClock clock,int minutes){for(int i=0;i<minutes;i++)clock.Advance(clock.RealSecondsPerSimulatedMinute);}
  private static (RecruitmentCoordinator coordinator,Candidate candidate,SimulationClock clock,FakeRouter router) Setup(ProfessionalRole role){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(1)),router,new RecruitmentConfiguration(5,999,999));var person=Person(Guid.NewGuid().ToString(),role);var candidate=new Candidate(person,1500);router.NextCandidate=candidate;coordinator.Dispose();coordinator=new RecruitmentCoordinator(clock,new FixedGenerator(candidate),router,new RecruitmentConfiguration(5,999,999));var generated=coordinator.TryGenerateArrival();return(coordinator,generated,clock,router);}
  private static PersonProfile Person(string id,ProfessionalRole role)=>new PersonProfile(id,"Test Talent",new SimulationDateTime(1900,1,1,0,0),role,new TalentProfile(60,70,new[]{new GenreExperience("drama",42)}),new[]{PersonTraitIds.Disciplined});
  private sealed class FixedGenerator:CandidateGenerator{private readonly Candidate _candidate;public FixedGenerator(Candidate candidate):base(new SeededRandomSource(1))=>_candidate=candidate;public override Candidate Generate(SimulationDateTime time)=>_candidate;}
  private sealed class FakeRouter:ICandidateWorldRouter{private int _slot;private bool _operational=true;private readonly List<Action> _pendingArrivals=new List<Action>();public Candidate NextCandidate;public CandidateRouteResult ArrivalResult=CandidateRouteResult.Started;public CandidateRouteResult DepartureResult=CandidateRouteResult.Started;public int Released;public int Capacity=6;public bool DeferArrival;public event Action OnRecruitmentLocationsChanged;public bool Operational{get=>_operational;set{if(_operational==value)return;_operational=value;OnRecruitmentLocationsChanged?.Invoke();}}public CandidateRouteResult RouteToRecruitmentLocation(Candidate c,Action<CandidateRouteResult,int> done){if(ArrivalResult==CandidateRouteResult.Started){int slot=_slot++;if(DeferArrival)_pendingArrivals.Add(()=>done(CandidateRouteResult.Started,slot));else done(CandidateRouteResult.Started,slot);}return ArrivalResult;}public void CompleteArrivals(){foreach(var arrival in _pendingArrivals)arrival();_pendingArrivals.Clear();}public CandidateRouteResult RouteToExit(Candidate c,Action<CandidateRouteResult,int> done){if(DepartureResult==CandidateRouteResult.Started)done(CandidateRouteResult.Started,-1);return DepartureResult;}public bool IsRecruitmentLocationOperational(RecruitmentCategory category)=>Operational;public int GetWaitingCapacity(RecruitmentCategory category)=>Capacity;public void ReleaseCandidate(Candidate c)=>Released++;}
 }
}
