using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using SilverScreen.Domain;
using SilverScreen.Domain.Finance;
using SilverScreen.Domain.Recruitment;
using SilverScreen.Domain.Time;
namespace SilverScreen.Tests
{
 public sealed class RecruitmentTests
 {
  private static SimulationDateTime Now=>new SimulationDateTime(1930,1,1,8,0);
  [Test] public void PersonAgeUsesSimulationDate(){var p=Person("p",ProfessionalRole.Actor);Assert.AreEqual(30,p.GetAge(Now));Assert.AreEqual(29,p.GetAge(new SimulationDateTime(1929,12,31,0,0)));}
  [Test] public void TalentStoresStableGenreExperienceAndTraits(){var p=Person("p",ProfessionalRole.Actor);Assert.AreEqual(42,p.Talent.GetGenreExperience("drama"));CollectionAssert.Contains(p.TraitIds,PersonTraitIds.Disciplined);}
  [Test] public void GeneratorIsDeterministicForKnownSeed(){var a=new CandidateGenerator(new SeededRandomSource(77)).Generate(Now);var b=new CandidateGenerator(new SeededRandomSource(77)).Generate(Now);Assert.AreEqual(a.Person.Id,b.Person.Id);Assert.AreEqual(a.Person.Name,b.Person.Name);Assert.AreEqual(a.Person.ProfessionalRole,b.Person.ProfessionalRole);Assert.AreEqual(a.SalaryExpectation,b.SalaryExpectation);}
  [Test] public void GeneratedCandidatesHaveValidRoleSalaryAndTraits(){var g=new CandidateGenerator(new SeededRandomSource(12));for(int i=0;i<30;i++){var c=g.Generate(Now);Assert.Contains(c.Person.ProfessionalRole,new[]{ProfessionalRole.Actor,ProfessionalRole.Director,ProfessionalRole.Extra});Assert.Greater(c.SalaryExpectation,0);Assert.That(c.Person.TraitIds.Count,Is.InRange(1,3));}}
  [Test] public void GeneratorCanProduceVaryingExperience(){var g=new CandidateGenerator(new SeededRandomSource(99));var values=Enumerable.Range(0,40).Select(_=>g.Generate(Now).Person.Talent.GetGenreExperience("drama")).Distinct().Count();Assert.Greater(values,3);}
  [Test] public void CandidateLifecycleAcceptsOnlyValidTransitions(){var c=new Candidate(Person("p",ProfessionalRole.Actor),1000);Assert.IsFalse(c.MarkHired());Assert.IsTrue(c.MarkWaiting(0));Assert.IsFalse(c.MarkWaiting(1));Assert.IsTrue(c.BeginDeparture());Assert.IsFalse(c.MarkHired());Assert.IsTrue(c.MarkGone());}
  [Test] public void HirePreservesPersonIdentityAndCreatesEmployee(){var setup=Setup(ProfessionalRole.Actor);var id=setup.candidate.Person.Id;var employee=setup.coordinator.Hire(setup.candidate);Assert.AreEqual(CandidateStatus.Hired,setup.candidate.Status);Assert.AreSame(setup.candidate.Person,employee.Person);Assert.AreEqual(id,employee.Id);Assert.AreEqual(EmployeeRole.Actor,employee.Role);}
  [Test] public void DirectorAndExtraMapToCorrectEmployeeRoles(){var director=Setup(ProfessionalRole.Director);Assert.AreEqual(EmployeeRole.Director,director.coordinator.Hire(director.candidate).Role);var extra=Setup(ProfessionalRole.Extra);Assert.AreEqual(EmployeeRole.Extra,extra.coordinator.Hire(extra.candidate).Role);}
  [Test] public void CandidateIsNotPayrollUntilHiredAndSalaryProcessesOnce(){var setup=Setup(ProfessionalRole.Actor);var employees=new List<Employee>();var finances=new StudioFinances(Now,Money.FromDollars(10000));using var accounting=new StudioAccountingService(setup.clock,finances,()=>employees,()=>Array.Empty<BuildingUpkeepDefinition>());Assert.AreEqual(Money.Zero,accounting.EstimatedMonthlyPayroll);var employee=setup.coordinator.Hire(setup.candidate);employees.Add(employee);Assert.AreEqual(Money.FromDollars(employee.Salary),accounting.EstimatedMonthlyPayroll);var date=new SimulationDateTime(1930,2,1,0,0);Assert.IsTrue(accounting.ProcessMonthlyAccounting(date));Assert.IsFalse(accounting.ProcessMonthlyAccounting(date));Assert.AreEqual(1,finances.Transactions.Count(x=>x.Category==FinancialTransactionCategory.EmployeeSalary));}
  [Test] public void RejectionRoutesCandidateToGone(){var setup=Setup(ProfessionalRole.Actor);Assert.IsTrue(setup.coordinator.Reject(setup.candidate));Assert.AreEqual(CandidateStatus.Gone,setup.candidate.Status);Assert.IsEmpty(setup.coordinator.Candidates);}
  [Test] public void ArrivalRoutingFailureRemovesCandidateSafely(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter{ArrivalResult=CandidateRouteResult.NavigationRejected};using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(1)),router,new RecruitmentConfiguration());var c=coordinator.TryGenerateArrival();Assert.AreEqual(CandidateStatus.Gone,c.Status);CollectionAssert.DoesNotContain(coordinator.Candidates,c);Assert.AreEqual(1,router.Released);}
  [Test] public void DepartureRoutingFailureRemovesCandidateSafely(){var setup=Setup(ProfessionalRole.Actor);setup.router.DepartureResult=CandidateRouteResult.NavigationRejected;Assert.IsTrue(setup.coordinator.Reject(setup.candidate));Assert.AreEqual(CandidateStatus.Gone,setup.candidate.Status);Assert.IsEmpty(setup.coordinator.Candidates);}
  [Test] public void CapacityIsRespectedAndWaitingSlotsAreUnique(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(3)),router,new RecruitmentConfiguration(2,999,999));var a=coordinator.TryGenerateArrival();var b=coordinator.TryGenerateArrival();Assert.IsNull(coordinator.TryGenerateArrival());Assert.AreNotEqual(a.WaitingPositionIndex,b.WaitingPositionIndex);}
  [Test] public void WaitingCandidateAutomaticallyExpires(){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();using var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(4)),router,new RecruitmentConfiguration(5,999,60));var c=coordinator.TryGenerateArrival();for(int i=0;i<60;i++)clock.Advance(.05f);Assert.AreEqual(CandidateStatus.Gone,c.Status);CollectionAssert.DoesNotContain(coordinator.Candidates,c);}
  private static (RecruitmentCoordinator coordinator,Candidate candidate,SimulationClock clock,FakeRouter router) Setup(ProfessionalRole role){var clock=new SimulationClock(realSecondsPerSimulatedMinute:.05f);var router=new FakeRouter();var coordinator=new RecruitmentCoordinator(clock,new CandidateGenerator(new SeededRandomSource(1)),router,new RecruitmentConfiguration(5,999,999));var person=Person(Guid.NewGuid().ToString(),role);var candidate=new Candidate(person,1500);router.NextCandidate=candidate;coordinator.Dispose();coordinator=new RecruitmentCoordinator(clock,new FixedGenerator(candidate),router,new RecruitmentConfiguration(5,999,999));var generated=coordinator.TryGenerateArrival();return(coordinator,generated,clock,router);}
  private static PersonProfile Person(string id,ProfessionalRole role)=>new PersonProfile(id,"Test Talent",new SimulationDateTime(1900,1,1,0,0),role,new TalentProfile(60,70,new[]{new GenreExperience("drama",42)}),new[]{PersonTraitIds.Disciplined});
  private sealed class FixedGenerator:CandidateGenerator{private readonly Candidate _candidate;public FixedGenerator(Candidate candidate):base(new SeededRandomSource(1))=>_candidate=candidate;public override Candidate Generate(SimulationDateTime time)=>_candidate;}
  private sealed class FakeRouter:ICandidateWorldRouter{private int _slot;public Candidate NextCandidate;public CandidateRouteResult ArrivalResult=CandidateRouteResult.Started;public CandidateRouteResult DepartureResult=CandidateRouteResult.Started;public int Released;public CandidateRouteResult RouteToStageSchool(Candidate c,Action<CandidateRouteResult,int> done){if(ArrivalResult==CandidateRouteResult.Started)done(CandidateRouteResult.Started,_slot++);return ArrivalResult;}public CandidateRouteResult RouteToExit(Candidate c,Action<CandidateRouteResult,int> done){if(DepartureResult==CandidateRouteResult.Started)done(CandidateRouteResult.Started,-1);return DepartureResult;}public void ReleaseCandidate(Candidate c)=>Released++;}
 }
}